packages:
  - playground

configDependencies:
  '@pnpm/plugin-better-defaults': 0.1.0+sha512-aWj7Jv9NcNs/OoazrxP6QspLgKRZ2PHj6wPris6ZCEqmXw+Z8zK59KLzl9NBFGRCO4PNA9pwDWLu+8N3NiqUAQ==

engineStrict: true

hoistWorkspacePackages: true

patchedDependencies:
  '@rspack/core@2.0.0-beta.2': patches/@rspack__core@2.0.0-beta.2.patch

publicHoistPattern: []

strictPeerDependencies: true
